custom:
  - https://www.paypal.com/donate/?business=CE2H5ZMBQKY9E&no_recurring=0&item_name=Thank+you+for+your+support%21+Your+donations+help+me+continue+to+do+the+work+I+love%21+I+hope+you+enjoy.+Be+sure+to+share%21&currency_code=USD
